### PR TITLE
TypeError Cannot assign string to property ContactForm::$attachFiles of ty…

### PR DESCRIPTION
**Pull request by githubjeka**
When empty Contract form uploaded

PHP. 8.0.21

image

Fixed typehinting from ?array to mixed

image

### CODE REVIEW

**Comment by xepozz** [comment]
Did you find a reason of this error?

**Comment by githubjeka** [comment]
`$_POST['attachFiles']  = ''` 
When submiting empty form

**Comment by xepozz** [comment]
Isn't it better to extend the type with `| string`?

**Comment by githubjeka** [comment]
Contract form havent `enctype="multipart/form-data"`
some time ago it was...

Why does it have to be explicit now via `enctypeMultipartFormData`?

```php
                   <?= Form::tag()
                        ->post($url->generate('site/contact'))
                        ->csrf($csrf)
                        ->enctypeMultipartFormData()
                        ->id('form-contact')
                        ->open()
                    ?>
```

**Pull request closed without merging**
