### PR TITLE
Add Indonesian Language

### PR DESCRIPTION
**Pull request by chanurholis**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #466

### CODE REVIEW

**Review by xepozz — APPROVED** [review]

**Comment by xepozz** [comment]
@chanurholis Would you like to participate in translation when we add more phrases?

**Comment by chanurholis** [comment]
> Would you like to participate in translation when we add more phrases?

hi @xepozz 👋🏻

Of course I really want to help when I have free time.

**Comment by samdark** [comment]
Thanks!

**Comment by chanurholis** [comment]
> Thanks!

hi @samdark 

Your welcome!

**Pull request merged**
