### PR TITLE
add slovak language 

### PR DESCRIPTION
**Pull request by evan70**
add slovak language >	modified:   resources/messages/id/app.php
add slovak language >	modified:   resources/messages/ru/app.php
add slovak language >	new file:   resources/messages/sk/app.php
add slovak language >	modified:   views/layout/main.php

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Review by xepozz — APPROVED** [review]

**Review by githubjeka — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Comment by alamagus** [comment]
missing sk [here](https://github.com/yiisoft/demo/blob/50ffbf7d812b2cc4ffe6df675edca7d7d05f0997/config/params.php#L27)

**Comment by alamagus** [comment]
Screenshot from 2022-08-12 08-22-02
Screenshot from 2022-08-12 08-21-49

I find it somewhat inconsistent. Mb it'd be worth picking out common keys into, say, messages/common
```php
return [
    'layout.language.english' => 'English',
    'layout.language.russian' => 'Русский',
    'layout.language.slovak' => 'Slovenský',
    'layout.language.indonesian' => 'Bahasa',
];
```

**Comment by vjik** [comment]
> missing sk [here](https://github.com/yiisoft/demo/blob/50ffbf7d812b2cc4ffe6df675edca7d7d05f0997/config/params.php#L27)

Yes, you are right. Can you create PR?

**Comment by vjik** [comment]
> I find it somewhat inconsistent. Mb it'd be worth picking out common keys into, say, messages/common

Created issue: https://github.com/yiisoft/demo/issues/495

**Pull request merged**
